// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwiknaGx4ve0wIowP1DcuGTntSy8Ee-N0',
    appId: '1:875013596630:web:9180f94b8b5db48d973077',
    messagingSenderId: '875013596630',
    projectId: 'crudapp-d7669',
    authDomain: 'crudapp-d7669.firebaseapp.com',
    storageBucket: 'crudapp-d7669.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoqAPjE4RUe-8VgZ2O7KUE8OMLtHspnyY',
    appId: '1:875013596630:android:23229a479a506e20973077',
    messagingSenderId: '875013596630',
    projectId: 'crudapp-d7669',
    storageBucket: 'crudapp-d7669.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtbsLKjsSbHO5rPyzzZbHOx2syT2dHC-c',
    appId: '1:875013596630:ios:a095c70028e0442a973077',
    messagingSenderId: '875013596630',
    projectId: 'crudapp-d7669',
    storageBucket: 'crudapp-d7669.appspot.com',
    iosClientId: '875013596630-e9hqk1jvl23ma9pse5bag1957pmj7rgt.apps.googleusercontent.com',
    iosBundleId: 'badiul.dev.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtbsLKjsSbHO5rPyzzZbHOx2syT2dHC-c',
    appId: '1:875013596630:ios:1b069746caffdfe8973077',
    messagingSenderId: '875013596630',
    projectId: 'crudapp-d7669',
    storageBucket: 'crudapp-d7669.appspot.com',
    iosClientId: '875013596630-3cd8p6jddvvt1iu65d27i6tdkfd3nb42.apps.googleusercontent.com',
    iosBundleId: 'badiul.dev.firebaseCrud.RunnerTests',
  );
}
